# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/link/Documents/Python/HoSoBenhAn/res/ui/Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 785)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.boxContainer = QtWidgets.QFrame(self.centralwidget)
        self.boxContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.boxContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.boxContainer.setObjectName("boxContainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.boxContainer)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MenuLeftFrame = QtWidgets.QFrame(self.boxContainer)
        self.MenuLeftFrame.setMinimumSize(QtCore.QSize(70, 0))
        self.MenuLeftFrame.setMaximumSize(QtCore.QSize(70, 16777215))
        self.MenuLeftFrame.setStyleSheet("QFrame#MenuLeftFrame {\n"
"    background-color: rgb(3,14,22);\n"
"}")
        self.MenuLeftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MenuLeftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuLeftFrame.setObjectName("MenuLeftFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.MenuLeftFrame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LeftFrame_2 = QtWidgets.QFrame(self.MenuLeftFrame)
        self.LeftFrame_2.setStyleSheet("color: white;")
        self.LeftFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LeftFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftFrame_2.setObjectName("LeftFrame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.LeftFrame_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.BottomLeftFrame_2 = QtWidgets.QFrame(self.LeftFrame_2)
        self.BottomLeftFrame_2.setMaximumSize(QtCore.QSize(16777215, 113))
        self.BottomLeftFrame_2.setStyleSheet("background-color: rgba(3,14,22,255);\n"
"border-bottom-left-radius: 20px;")
        self.BottomLeftFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BottomLeftFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomLeftFrame_2.setObjectName("BottomLeftFrame_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.BottomLeftFrame_2)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setHorizontalSpacing(0)
        self.gridLayout_13.setVerticalSpacing(7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.btn_logout = QtWidgets.QPushButton(self.BottomLeftFrame_2)
        self.btn_logout.setMinimumSize(QtCore.QSize(64, 30))
        self.btn_logout.setStyleSheet("QPushButton#btn_logout {\n"
"    background-repeat: none;\n"
"    background-position: center top;\n"
"    border-top: 10px solid transparent;\n"
"    font:8pt \"Open Sans\";\n"
"}\n"
"QPushButton#btn_logout:hover {\n"
"    background-repeat: none;\n"
"    background-position: center top;\n"
"    background-color:  rgba(44,62,76,255);\n"
"    border-top: 10px solid transparent;\n"
"    border-radius:5px;\n"
"    margin-left: 3px;\n"
"    margin-right: 3px;\n"
"    font: 8pt \"Open Sans\";\n"
" }")
        self.btn_logout.setObjectName("btn_logout")
        self.gridLayout_13.addWidget(self.btn_logout, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.BottomLeftFrame_2, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.LeftBtnFrame_2 = QtWidgets.QFrame(self.LeftFrame_2)
        self.LeftBtnFrame_2.setMaximumSize(QtCore.QSize(16777215, 470))
        self.LeftBtnFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LeftBtnFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftBtnFrame_2.setObjectName("LeftBtnFrame_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.LeftBtnFrame_2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setHorizontalSpacing(0)
        self.gridLayout_7.setVerticalSpacing(10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.UserLeftBtn_2 = QtWidgets.QPushButton(self.LeftBtnFrame_2)
        self.UserLeftBtn_2.setMinimumSize(QtCore.QSize(60, 70))
        self.UserLeftBtn_2.setStyleSheet("QPushButton#UserLeftBtn_2{\n"
"    background-image: url(:/images/res/drawable/icons/user_line.png);\n"
"    background-repeat: none;\n"
"    background-position: center top;\n"
"    border-top: 10px solid transparent;\n"
"    padding-top: 20px;\n"
"    font: 8pt \"Open Sans\";\n"
"}\n"
"QPushButton#UserLeftBtn_2:hover {\n"
"    background-image: url(:/images/res/drawable/icons/user.png);\n"
"    background-repeat: none;\n"
"    background-position: center top;\n"
"    background-color:  rgba(44,62,76,255);\n"
"    border-top: 10px solid transparent;\n"
"    border-radius:15px;\n"
"    margin-left: 3px;\n"
"    margin-right: 3px;\n"
"    padding-top: 20px;\n"
"    font: 8pt \"Open Sans\";\n"
" }")
        self.UserLeftBtn_2.setObjectName("UserLeftBtn_2")
        self.gridLayout_7.addWidget(self.UserLeftBtn_2, 0, 0, 1, 1)
        self.ManageLeftBtn_2 = QtWidgets.QPushButton(self.LeftBtnFrame_2)
        self.ManageLeftBtn_2.setMinimumSize(QtCore.QSize(60, 70))
        self.ManageLeftBtn_2.setStyleSheet("QPushButton#ManageLeftBtn_2 {\n"
"   background-image: url(:/images/res/drawable/icons/manage_line.png);\n"
"    background-repeat: none;\n"
"    background-position: center top;\n"
"    border-top: 10px solid transparent;\n"
"    padding-top: 20px;\n"
"    font: 8pt \"Open Sans\";\n"
"}\n"
"QPushButton#ManageLeftBtn_2:hover {\n"
"    background-image: url(:/images/res/drawable/icons/manage.png);\n"
"    background-repeat: none;\n"
"    background-position: center top;\n"
"    background-color:  rgba(44,62,76,255);\n"
"    border-top: 10px solid transparent;\n"
"    border-radius:15px;\n"
"    margin-left: 3px;\n"
"    margin-right: 3px;\n"
"    padding-top: 20px;\n"
"    font: 8pt \"Open Sans\";\n"
" }")
        self.ManageLeftBtn_2.setObjectName("ManageLeftBtn_2")
        self.gridLayout_7.addWidget(self.ManageLeftBtn_2, 1, 0, 1, 1)
        self.SettingLeftBtn_2 = QtWidgets.QPushButton(self.LeftBtnFrame_2)
        self.SettingLeftBtn_2.setMinimumSize(QtCore.QSize(60, 70))
        self.SettingLeftBtn_2.setStyleSheet("QPushButton#SettingLeftBtn_2 {background-image: url(:/images/res/drawable/icons/device_line.png);\n"
"    background-repeat: none;\n"
"    background-position: center top;\n"
"    border-top: 10px solid transparent;\n"
"    padding-top: 20px;\n"
"    font: 8pt \"Open Sans\";\n"
"}\n"
"QPushButton#SettingLeftBtn_2:hover {\n"
"    background-image: url(:/images/res/drawable/icons/device.png);\n"
"    background-repeat: none;\n"
"    background-position: center top;\n"
"    background-color:  rgba(44,62,76,255);\n"
"    border-top: 10px solid transparent;\n"
"    border-radius:15px;\n"
"    margin-left: 3px;\n"
"    margin-right: 3px;\n"
"    padding-top: 20px;\n"
"    font: 8pt \"Open Sans\";\n"
" }")
        self.SettingLeftBtn_2.setObjectName("SettingLeftBtn_2")
        self.gridLayout_7.addWidget(self.SettingLeftBtn_2, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.LeftBtnFrame_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.LeftFrame_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.MenuLeftFrame)
        self.BodyContainer = QtWidgets.QFrame(self.boxContainer)
        self.BodyContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BodyContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BodyContainer.setObjectName("BodyContainer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.BodyContainer)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidgetHome = QtWidgets.QStackedWidget(self.BodyContainer)
        self.stackedWidgetHome.setObjectName("stackedWidgetHome")
        self.managerPage = QtWidgets.QWidget()
        self.managerPage.setObjectName("managerPage")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.managerPage)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.containerManager = QtWidgets.QFrame(self.managerPage)
        self.containerManager.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.containerManager.setFrameShadow(QtWidgets.QFrame.Raised)
        self.containerManager.setObjectName("containerManager")
        self.gridLayout_9.addWidget(self.containerManager, 0, 0, 1, 1)
        self.stackedWidgetHome.addWidget(self.managerPage)
        self.userPage = QtWidgets.QWidget()
        self.userPage.setObjectName("userPage")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.userPage)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.containerUser = QtWidgets.QFrame(self.userPage)
        self.containerUser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.containerUser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.containerUser.setObjectName("containerUser")
        self.gridLayout_8.addWidget(self.containerUser, 0, 0, 1, 1)
        self.stackedWidgetHome.addWidget(self.userPage)
        self.trashPage = QtWidgets.QWidget()
        self.trashPage.setObjectName("trashPage")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.trashPage)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.containerTrashPage = QtWidgets.QFrame(self.trashPage)
        self.containerTrashPage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.containerTrashPage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.containerTrashPage.setObjectName("containerTrashPage")
        self.gridLayout_10.addWidget(self.containerTrashPage, 0, 0, 1, 1)
        self.stackedWidgetHome.addWidget(self.trashPage)
        self.gridLayout_2.addWidget(self.stackedWidgetHome, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.BodyContainer)
        self.gridLayout.addWidget(self.boxContainer, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidgetHome.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_logout.setText(_translate("MainWindow", "Đăng xuất"))
        self.UserLeftBtn_2.setText(_translate("MainWindow", "Quản Lý"))
        self.ManageLeftBtn_2.setText(_translate("MainWindow", "Người dùng"))
        self.SettingLeftBtn_2.setText(_translate("MainWindow", "Thùng rác"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
