# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Admin\Downloads\data\HoSoBenhAn\res\ui\Member.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(832, 538)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.VehicleTypeOptionFrame = QtWidgets.QFrame(self.frame)
        self.VehicleTypeOptionFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.VehicleTypeOptionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VehicleTypeOptionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VehicleTypeOptionFrame.setObjectName("VehicleTypeOptionFrame")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.VehicleTypeOptionFrame)
        self.gridLayout_43.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_43.setSpacing(0)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.VehicleTypeOptionBlankFrame_2 = QtWidgets.QFrame(self.VehicleTypeOptionFrame)
        self.VehicleTypeOptionBlankFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VehicleTypeOptionBlankFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VehicleTypeOptionBlankFrame_2.setObjectName("VehicleTypeOptionBlankFrame_2")
        self.btnAddMember = QtWidgets.QPushButton(self.VehicleTypeOptionBlankFrame_2)
        self.btnAddMember.setGeometry(QtCore.QRect(0, 5, 40, 40))
        self.btnAddMember.setMinimumSize(QtCore.QSize(40, 40))
        self.btnAddMember.setMaximumSize(QtCore.QSize(40, 40))
        self.btnAddMember.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddMember.setToolTip("")
        self.btnAddMember.setStyleSheet("background-color: rgb(3, 14, 22);\n"
"    color: white;\n"
"    border-radius: 20px;\n"
"    font: 87 10pt \"Segoe UI Black\";\n"
"    background-image: url(:/images/res/drawable/icons/add.png);\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"")
        self.btnAddMember.setText("")
        self.btnAddMember.setObjectName("btnAddMember")
        self.edtSearchMemberType = QtWidgets.QLineEdit(self.VehicleTypeOptionBlankFrame_2)
        self.edtSearchMemberType.setGeometry(QtCore.QRect(70, 5, 300, 40))
        self.edtSearchMemberType.setMinimumSize(QtCore.QSize(250, 40))
        self.edtSearchMemberType.setMaximumSize(QtCore.QSize(300, 16777215))
        self.edtSearchMemberType.setStyleSheet("color: black;\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"    background-image:url(:/images/res/drawable/icons/search_line_padding-left.png);\n"
"    background-position: left center;\n"
"    background-repeat: none;\n"
"    padding-left: 40px;\n"
"    font: 10pt \"Open Sans\";\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;")
        self.edtSearchMemberType.setObjectName("edtSearchMemberType")
        self.gridLayout_43.addWidget(self.VehicleTypeOptionBlankFrame_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.VehicleTypeOptionFrame)
        self.tbMember = QtWidgets.QTableWidget(self.frame)
        self.tbMember.setStyleSheet("QTableWidget#tbMember {\n"
"    background-color: white;\n"
"    padding: 15px;\n"
"    border-radius: 15px;\n"
"    font: 11pt \"Open Sans\";\n"
"}\n"
"QTableWidget::item {\n"
"    \n"
"}\n"
"\n"
"QTableWidget::section {\n"
"    height: 50px;\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: white;\n"
"color:#000;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    border: none;\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 81 12pt \"Open Sans Condensed ExtraBold\";\n"
"\n"
"}\n"
"QTableWidget::horizontalHeader {\n"
"\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"}\n"
"")
        self.tbMember.setLineWidth(1)
        self.tbMember.setDragDropOverwriteMode(True)
        self.tbMember.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tbMember.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tbMember.setTextElideMode(QtCore.Qt.ElideRight)
        self.tbMember.setShowGrid(False)
        self.tbMember.setGridStyle(QtCore.Qt.SolidLine)
        self.tbMember.setWordWrap(True)
        self.tbMember.setObjectName("tbMember")
        self.tbMember.setColumnCount(8)
        self.tbMember.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tbMember.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbMember.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbMember.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbMember.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbMember.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbMember.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tbMember.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbMember.setHorizontalHeaderItem(7, item)
        self.tbMember.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tbMember)
        self.VEhicleTypeBlankOptionStatusFrame = QtWidgets.QFrame(self.frame)
        self.VEhicleTypeBlankOptionStatusFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.VEhicleTypeBlankOptionStatusFrame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.VEhicleTypeBlankOptionStatusFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VEhicleTypeBlankOptionStatusFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VEhicleTypeBlankOptionStatusFrame.setObjectName("VEhicleTypeBlankOptionStatusFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.VEhicleTypeBlankOptionStatusFrame)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbTottal = QtWidgets.QLabel(self.VEhicleTypeBlankOptionStatusFrame)
        self.lbTottal.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lbTottal.setFont(font)
        self.lbTottal.setObjectName("lbTottal")
        self.horizontalLayout.addWidget(self.lbTottal)
        self.lbPage = QtWidgets.QLabel(self.VEhicleTypeBlankOptionStatusFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lbPage.setFont(font)
        self.lbPage.setObjectName("lbPage")
        self.horizontalLayout.addWidget(self.lbPage)
        self.frame_2 = QtWidgets.QFrame(self.VEhicleTypeBlankOptionStatusFrame)
        self.frame_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnBackPage = QtWidgets.QPushButton(self.frame_2)
        self.btnBackPage.setMinimumSize(QtCore.QSize(0, 30))
        self.btnBackPage.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnBackPage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBackPage.setStyleSheet("background-color:#000;")
        self.btnBackPage.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/res/drawable/icons/back_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBackPage.setIcon(icon)
        self.btnBackPage.setObjectName("btnBackPage")
        self.horizontalLayout_2.addWidget(self.btnBackPage)
        self.btnNextPage = QtWidgets.QPushButton(self.frame_2)
        self.btnNextPage.setMinimumSize(QtCore.QSize(0, 30))
        self.btnNextPage.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnNextPage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNextPage.setStyleSheet("background-color:#000;")
        self.btnNextPage.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/res/drawable/icons/next_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNextPage.setIcon(icon1)
        self.btnNextPage.setObjectName("btnNextPage")
        self.horizontalLayout_2.addWidget(self.btnNextPage)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.VEhicleTypeBlankOptionStatusFrame)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.edtSearchMemberType.setPlaceholderText(_translate("Form", "Nhập tên hoặc CCCD..."))
        item = self.tbMember.horizontalHeaderItem(0)
        item.setText(_translate("Form", "STT"))
        item = self.tbMember.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Họ và tên"))
        item = self.tbMember.horizontalHeaderItem(2)
        item.setText(_translate("Form", "CCCD"))
        item = self.tbMember.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Nguyên quán"))
        item = self.tbMember.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Người nhà"))
        item = self.tbMember.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Ngày nhập"))
        item = self.tbMember.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Hình ảnh"))
        self.lbTottal.setText(_translate("Form", "Tổng: 0"))
        self.lbPage.setText(_translate("Form", "Trang: 0/0"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
